spring.application.name=Billing_webApplication

spring.datasource.url=jdbc:mysql://localhost:3306/Billing_Software
spring.datasource.username=root
spring.datasource.password=7685
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


stripe.public.key=${STRIPE_PUBLIC_KEY}
stripe.secret.key=${STRIPE_SECRET_KEY}
